/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ParcelasRouteImport } from './routes/parcelas'
import { Route as FallecidosRouteImport } from './routes/fallecidos'
import { Route as IndexRouteImport } from './routes/index'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelasRoute = ParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => rootRouteImport,
} as any)
const FallecidosRoute = FallecidosRouteImport.update({
  id: '/fallecidos',
  path: '/fallecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fallecidos': typeof FallecidosRoute
  '/parcelas': typeof ParcelasRoute
  '/plano': typeof PlanoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fallecidos': typeof FallecidosRoute
  '/parcelas': typeof ParcelasRoute
  '/plano': typeof PlanoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fallecidos': typeof FallecidosRoute
  '/parcelas': typeof ParcelasRoute
  '/plano': typeof PlanoRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fallecidos' | '/parcelas' | '/plano' | '/reportes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fallecidos' | '/parcelas' | '/plano' | '/reportes'
  id: '__root__' | '/' | '/fallecidos' | '/parcelas' | '/plano' | '/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FallecidosRoute: typeof FallecidosRoute
  ParcelasRoute: typeof ParcelasRoute
  PlanoRoute: typeof PlanoRoute
  ReportesRoute: typeof ReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelas': {
      id: '/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof ParcelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallecidos': {
      id: '/fallecidos'
      path: '/fallecidos'
      fullPath: '/fallecidos'
      preLoaderRoute: typeof FallecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FallecidosRoute: FallecidosRoute,
  ParcelasRoute: ParcelasRoute,
  PlanoRoute: PlanoRoute,
  ReportesRoute: ReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
